# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_mark_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='data_time',
            new_name='datetime',
        ),
    ]
