# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170619_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesubject',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
